"""Initial tables

Revision ID: b03664ce39fb
Revises: 
Create Date: 2026-08-28 20:38:10.934185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03664ce39fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('VICTIM', 'COUNSELOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('counselor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_counselor_profiles_id'), 'counselor_profiles', ['id'], unique=False)
    op.create_table('victim_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('nhaa_case_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('current_distress_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('counselor_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['counselor_id'], ['counselor_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_victim_profiles_id'), 'victim_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_victim_profiles_nhaa_case_id'), 'victim_profiles', ['nhaa_case_id'], unique=True)
    op.create_table('interaction_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('victim_id', sa.UUID(), nullable=True),
    sa.Column('interaction_type', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('voice_stress_level', sa.Float(), nullable=True),
    sa.Column('calculated_distress', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['victim_id'], ['victim_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_critical_alerts', 'interaction_logs', ['calculated_distress', sa.literal_column('timestamp DESC')], unique=False, postgresql_where=sa.text('calculated_distress >= 0.7'))
    op.create_index('idx_timestamp_desc_distress', 'interaction_logs', [sa.literal_column('timestamp DESC'), 'calculated_distress'], unique=False)
    op.create_index('idx_victim_timestamp_desc', 'interaction_logs', ['victim_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_interaction_logs_id'), 'interaction_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_logs_id'), table_name='interaction_logs')
    op.drop_index('idx_victim_timestamp_desc', table_name='interaction_logs')
    op.drop_index('idx_timestamp_desc_distress', table_name='interaction_logs')
    op.drop_index('idx_critical_alerts', table_name='interaction_logs', postgresql_where=sa.text('calculated_distress >= 0.7'))
    op.drop_table('interaction_logs')
    op.drop_index(op.f('ix_victim_profiles_nhaa_case_id'), table_name='victim_profiles')
    op.drop_index(op.f('ix_victim_profiles_id'), table_name='victim_profiles')
    op.drop_table('victim_profiles')
    op.drop_index(op.f('ix_counselor_profiles_id'), table_name='counselor_profiles')
    op.drop_table('counselor_profiles')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
